namespace GladBot
{
	//TODO: What is this?
	public enum SpellModOp
	{
		SPELLMOD_DAMAGE = 0,
		SPELLMOD_DURATION = 1,
		SPELLMOD_THREAT = 2,
		SPELLMOD_EFFECT1 = 3,
		SPELLMOD_CHARGES = 4,
		SPELLMOD_RANGE = 5,
		SPELLMOD_RADIUS = 6,
		SPELLMOD_CRITICAL_CHANCE = 7,
		SPELLMOD_ALL_EFFECTS = 8,
		SPELLMOD_NOT_LOSE_CASTING_TIME = 9,
		SPELLMOD_CASTING_TIME = 10,
		SPELLMOD_COOLDOWN = 11,
		SPELLMOD_EFFECT2 = 12,
		SPELLMOD_IGNORE_ARMOR = 13,
		SPELLMOD_COST = 14,
		SPELLMOD_CRIT_DAMAGE_BONUS = 15,
		SPELLMOD_RESIST_MISS_CHANCE = 16,
		SPELLMOD_JUMP_TARGETS = 17,
		SPELLMOD_CHANCE_OF_SUCCESS = 18,
		SPELLMOD_ACTIVATION_TIME = 19,
		SPELLMOD_DAMAGE_MULTIPLIER = 20,
		SPELLMOD_GLOBAL_COOLDOWN = 21,
		SPELLMOD_DOT = 22,
		SPELLMOD_EFFECT3 = 23,
		SPELLMOD_BONUS_MULTIPLIER = 24,
		// spellmod 25
		SPELLMOD_PROC_PER_MINUTE = 26,
		SPELLMOD_VALUE_MULTIPLIER = 27,
		SPELLMOD_RESIST_DISPEL_CHANCE = 28,
		SPELLMOD_CRIT_DAMAGE_BONUS_2 = 29, //one not used spell
		SPELLMOD_SPELL_COST_REFUND_ON_FAIL = 30
	};
}