namespace FreecraftCore
{
	public enum UnitMods
	{
		UNIT_MOD_STAT_STRENGTH = 0,                  // UNIT_MOD_STAT_STRENGTH..UNIT_MOD_STAT_SPIRIT must be in existed order, it's accessed by index values of Stats enum.
		UNIT_MOD_STAT_AGILITY = 1,
		UNIT_MOD_STAT_STAMINA = 2,
		UNIT_MOD_STAT_INTELLECT = 3,
		UNIT_MOD_STAT_SPIRIT = 4,
		UNIT_MOD_HEALTH = 5,
		UNIT_MOD_MANA = 6,                  // UNIT_MOD_MANA..UNIT_MOD_RUNIC_POWER must be in existed order, it's accessed by index values of Powers enum.
		UNIT_MOD_RAGE = 7,
		UNIT_MOD_FOCUS = 8,
		UNIT_MOD_ENERGY = 9,
		UNIT_MOD_HAPPINESS = 10,
		UNIT_MOD_RUNE = 11,
		UNIT_MOD_RUNIC_POWER = 12,
		UNIT_MOD_ARMOR = 13,                 // UNIT_MOD_ARMOR..UNIT_MOD_RESISTANCE_ARCANE must be in existed order, it's accessed by index values of SpellSchools enum.
		UNIT_MOD_RESISTANCE_HOLY = 14,
		UNIT_MOD_RESISTANCE_FIRE = 15,
		UNIT_MOD_RESISTANCE_NATURE = 16,
		UNIT_MOD_RESISTANCE_FROST = 17,
		UNIT_MOD_RESISTANCE_SHADOW = 18,
		UNIT_MOD_RESISTANCE_ARCANE = 19,
		UNIT_MOD_ATTACK_POWER = 20,
		UNIT_MOD_ATTACK_POWER_RANGED = 21,
		UNIT_MOD_DAMAGE_MAINHAND = 22,
		UNIT_MOD_DAMAGE_OFFHAND = 23,
		UNIT_MOD_DAMAGE_RANGED = 24,
		UNIT_MOD_END = 25,
		// synonyms
		UNIT_MOD_STAT_START = UNIT_MOD_STAT_STRENGTH,
		UNIT_MOD_STAT_END = UNIT_MOD_STAT_SPIRIT + 1,
		UNIT_MOD_RESISTANCE_START = UNIT_MOD_ARMOR,
		UNIT_MOD_RESISTANCE_END = UNIT_MOD_RESISTANCE_ARCANE + 1,
		UNIT_MOD_POWER_START = UNIT_MOD_MANA,
		UNIT_MOD_POWER_END = UNIT_MOD_RUNIC_POWER + 1,
	};
}