// <auto-generated />
using FreecraftCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreecraftCore.DBC.Management.Migrations
{
    [DbContext(typeof(DataBaseClientFilesDatabaseContext))]
    [Migration("20180618001608_AddedManyDBCModels")]
    partial class AddedManyDBCModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FreecraftCore.ItemEntry", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InventorySlotType");

                    b.Property<int>("ItemClassId");

                    b.Property<int>("ItemDisplayId");

                    b.Property<int>("ItemSubClassId");

                    b.Property<int>("MaterialId");

                    b.Property<int>("SheathType");

                    b.Property<int>("SoundOverride");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("FreecraftCore.SkillLineAbilityEntry", b =>
                {
                    b.Property<int>("SkillLineAbilityId")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Classmask");

                    b.Property<uint>("ClassmaskNot");

                    b.Property<uint>("ForwardSpellid");

                    b.Property<uint>("MaxValue");

                    b.Property<uint>("MinValue");

                    b.Property<uint>("Racemask");

                    b.Property<uint>("RacemaskNot");

                    b.Property<uint>("RequiredSkillValue");

                    b.Property<uint>("SkillAquireMethod");

                    b.Property<uint>("SkillId");

                    b.Property<uint>("SpellId");

                    b.HasKey("SkillLineAbilityId");

                    b.ToTable("SkillLineAbility");
                });

            modelBuilder.Entity("FreecraftCore.SpellCastTimesEntry", b =>
                {
                    b.Property<int>("SpellCastTimeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CastTime");

                    b.Property<float>("CastTimePerLevel");

                    b.Property<int>("MinCastTime");

                    b.HasKey("SpellCastTimeId");

                    b.ToTable("SpellCastTime");
                });

            modelBuilder.Entity("FreecraftCore.SpellDifficultyEntry", b =>
                {
                    b.Property<int>("SpellDifficultyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Heroic10manSpellId");

                    b.Property<int>("Heroic25manSpellId");

                    b.Property<int>("Normal10manSpellId");

                    b.Property<int>("Normal25manSpellId");

                    b.HasKey("SpellDifficultyId");

                    b.ToTable("SpellDifficulty");
                });

            modelBuilder.Entity("FreecraftCore.SpellDurationEntry", b =>
                {
                    b.Property<int>("SpellDurationId")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Duration");

                    b.Property<uint>("DurationPerLevel");

                    b.Property<uint>("MaxDuration");

                    b.HasKey("SpellDurationId");

                    b.ToTable("SpellDuration");
                });

            modelBuilder.Entity("FreecraftCore.SpellEntry<string>", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("ActiveIconID");

                    b.Property<int>("AreaGroupId");

                    b.Property<uint>("Attributes");

                    b.Property<uint>("AttributesEx");

                    b.Property<uint>("AttributesEx2");

                    b.Property<uint>("AttributesEx3");

                    b.Property<uint>("AttributesEx4");

                    b.Property<uint>("AttributesEx5");

                    b.Property<uint>("AttributesEx6");

                    b.Property<uint>("AttributesEx7");

                    b.Property<uint>("AuraInterruptFlags");

                    b.Property<uint>("BaseLevel");

                    b.Property<uint>("CasterAuraSpell");

                    b.Property<int>("CasterAuraState");

                    b.Property<int>("CasterAuraStateNot");

                    b.Property<uint>("CastingTimeIndex");

                    b.Property<uint>("Category");

                    b.Property<uint>("CategoryRecoveryTime");

                    b.Property<uint>("ChannelInterruptFlags");

                    b.Property<uint>("Dispel");

                    b.Property<int>("DmgClass");

                    b.Property<uint>("DurationIndex");

                    b.Property<int>("EquippedItemClass");

                    b.Property<int>("EquippedItemInventoryTypeMask");

                    b.Property<int>("EquippedItemSubClassMask");

                    b.Property<uint>("ExcludeCasterAuraSpell");

                    b.Property<uint>("ExcludeTargetAuraSpell");

                    b.Property<uint>("FacingCasterFlags");

                    b.Property<uint>("InterruptFlags");

                    b.Property<uint>("ManaCost");

                    b.Property<uint>("ManaCostPercentage");

                    b.Property<uint>("ManaCostPerlevel");

                    b.Property<uint>("ManaPerSecond");

                    b.Property<uint>("ManaPerSecondPerLevel");

                    b.Property<uint>("MaxAffectedTargets");

                    b.Property<uint>("MaxLevel");

                    b.Property<uint>("MaxTargetLevel");

                    b.Property<int>("Mechanic");

                    b.Property<uint>("MinFactionId");

                    b.Property<uint>("MinReputation");

                    b.Property<uint>("ModalNextSpell");

                    b.Property<uint>("PowerDisplayId");

                    b.Property<uint>("PowerType");

                    b.Property<int>("PreventionType");

                    b.Property<uint>("ProcChance");

                    b.Property<uint>("ProcCharges");

                    b.Property<int>("ProcFlags");

                    b.Property<uint>("RangeIndex");

                    b.Property<uint>("RecoveryTime");

                    b.Property<uint>("RequiredAuraVision");

                    b.Property<uint>("RequiresSpellFocus");

                    b.Property<uint>("RuneCostID");

                    b.Property<int>("SchoolMask");

                    b.Property<float>("Speed");

                    b.Property<uint>("SpellDescriptionVariableID");

                    b.Property<uint>("SpellDifficultyId");

                    b.Property<int>("SpellFamilyName");

                    b.Property<uint>("SpellIconID");

                    b.Property<uint>("SpellLevel");

                    b.Property<uint>("SpellMissileID");

                    b.Property<uint>("SpellPriority");

                    b.Property<uint>("StackAmount");

                    b.Property<uint>("StanceBarOrder");

                    b.Property<ulong>("Stances");

                    b.Property<ulong>("StancesNot");

                    b.Property<uint>("StartRecoveryCategory");

                    b.Property<uint>("StartRecoveryTime");

                    b.Property<uint>("TargetAuraSpell");

                    b.Property<int>("TargetAuraState");

                    b.Property<int>("TargetAuraStateNot");

                    b.Property<int>("TargetCreatureType");

                    b.Property<uint>("Targets");

                    b.HasKey("SpellId");

                    b.ToTable("Spell");
                });

            modelBuilder.Entity("FreecraftCore.SpellRadiusEntry", b =>
                {
                    b.Property<uint>("SpellRadiusId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Radius");

                    b.Property<float>("Radius2");

                    b.Property<int>("Zero");

                    b.HasKey("SpellRadiusId");

                    b.ToTable("SpellRadius");
                });

            modelBuilder.Entity("FreecraftCore.SpellRangeEntry<string>", b =>
                {
                    b.Property<uint>("SpellRangeId")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Field5");

                    b.Property<float>("MaxRange");

                    b.Property<float>("MaxRangeFriendly");

                    b.Property<float>("MinRange");

                    b.Property<float>("MinRangeFriendly");

                    b.HasKey("SpellRangeId");

                    b.ToTable("SpellRange");
                });

            modelBuilder.Entity("FreecraftCore.SkillLineAbilityEntry", b =>
                {
                    b.OwnsOne("FreecraftCore.Vector2<uint>", "CharacterPoints", b1 =>
                        {
                            b1.Property<int>("SkillLineAbilityEntrySkillLineAbilityId");

                            b1.ToTable("SkillLineAbility");

                            b1.HasOne("FreecraftCore.SkillLineAbilityEntry")
                                .WithOne("CharacterPoints")
                                .HasForeignKey("FreecraftCore.Vector2<uint>", "SkillLineAbilityEntrySkillLineAbilityId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("FreecraftCore.SpellEntry<string>", b =>
                {
                    b.OwnsOne("FreecraftCore.Flags96<uint>", "SpellFamilyFlags", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("One");

                            b1.Property<uint>("Three");

                            b1.Property<uint>("Two");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("SpellFamilyFlags")
                                .HasForeignKey("FreecraftCore.Flags96<uint>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.RequiredReagentData", "ReagentsRequired", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("ReagentsRequired")
                                .HasForeignKey("FreecraftCore.RequiredReagentData", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("FreecraftCore.ReagentDataChunk<int>", "ReagentId", b2 =>
                                {
                                    b2.Property<int>("RequiredReagentDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Eight");

                                    b2.Property<int>("Five");

                                    b2.Property<int>("Four");

                                    b2.Property<int>("One");

                                    b2.Property<int>("Seven");

                                    b2.Property<int>("Six");

                                    b2.Property<int>("Three");

                                    b2.Property<int>("Two");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.RequiredReagentData")
                                        .WithOne("ReagentId")
                                        .HasForeignKey("FreecraftCore.ReagentDataChunk<int>", "RequiredReagentDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.ReagentDataChunk<uint>", "ReagentCount", b2 =>
                                {
                                    b2.Property<int>("RequiredReagentDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Eight");

                                    b2.Property<uint>("Five");

                                    b2.Property<uint>("Four");

                                    b2.Property<uint>("One");

                                    b2.Property<uint>("Seven");

                                    b2.Property<uint>("Six");

                                    b2.Property<uint>("Three");

                                    b2.Property<uint>("Two");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.RequiredReagentData")
                                        .WithOne("ReagentCount")
                                        .HasForeignKey("FreecraftCore.ReagentDataChunk<uint>", "RequiredReagentDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellTotemDataChunk<uint>", "Totem", b2 =>
                                {
                                    b2.Property<int>("RequiredReagentDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("One");

                                    b2.Property<uint>("Two");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.RequiredReagentData")
                                        .WithOne("Totem")
                                        .HasForeignKey("FreecraftCore.SpellTotemDataChunk<uint>", "RequiredReagentDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("FreecraftCore.SpellEffectData", "SpellEffectInformation", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("SpellEffectInformation")
                                .HasForeignKey("FreecraftCore.SpellEffectData", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<FreecraftCore.AuraType>", "EffectApplyAuraName", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectApplyAuraName")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<FreecraftCore.AuraType>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellEffect>", "Effect", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("Effect")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellEffect>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellMechanic>", "EffectMechanic", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectMechanic")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellMechanic>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<float>", "EffectMultipleValue", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<float>("Effect1");

                                    b2.Property<float>("Effect2");

                                    b2.Property<float>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectMultipleValue")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<float>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<float>", "EffectPointsPerComboPoint", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<float>("Effect1");

                                    b2.Property<float>("Effect2");

                                    b2.Property<float>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectPointsPerComboPoint")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<float>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<float>", "EffectRealPointsPerLevel", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<float>("Effect1");

                                    b2.Property<float>("Effect2");

                                    b2.Property<float>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectRealPointsPerLevel")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<float>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellTargetType>", "EffectImplicitTargetA", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectImplicitTargetA")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellTargetType>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellTargetType>", "EffectImplicitTargetB", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectImplicitTargetB")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<FreecraftCore.SpellTargetType>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<int>", "EffectBasePoints", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectBasePoints")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<int>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<int>", "EffectDieSides", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectDieSides")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<int>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<int>", "EffectMiscValue", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectMiscValue")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<int>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<int>", "EffectMiscValueB", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<int>("Effect1");

                                    b2.Property<int>("Effect2");

                                    b2.Property<int>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectMiscValueB")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<int>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectAmplitude", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectAmplitude")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectChainTarget", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectChainTarget")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectItemType", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectItemType")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectRadiusIndex", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectRadiusIndex")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectSpellClassMaskA", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectSpellClassMaskA")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectSpellClassMaskB", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectSpellClassMaskB")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectSpellClassMaskC", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectSpellClassMaskC")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("FreecraftCore.SpellEffectDataChunk<uint>", "EffectTriggerSpell", b2 =>
                                {
                                    b2.Property<int>("SpellEffectDataSpellEntry<string>SpellId");

                                    b2.Property<uint>("Effect1");

                                    b2.Property<uint>("Effect2");

                                    b2.Property<uint>("Effect3");

                                    b2.ToTable("Spell");

                                    b2.HasOne("FreecraftCore.SpellEffectData")
                                        .WithOne("EffectTriggerSpell")
                                        .HasForeignKey("FreecraftCore.SpellEffectDataChunk<uint>", "SpellEffectDataSpellEntry<string>SpellId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("FreecraftCore.SpellVisualData", "SpellVisual", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("One");

                            b1.Property<uint>("Two");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("SpellVisual")
                                .HasForeignKey("FreecraftCore.SpellVisualData", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "Description", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("Description")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "Rank", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("Rank")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "SpellName", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("SpellName")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "ToolTip", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("ToolTip")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.SpellEffectDataChunk<float>", "DamageCoeficient", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<float>("Effect1");

                            b1.Property<float>("Effect2");

                            b1.Property<float>("Effect3");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("DamageCoeficient")
                                .HasForeignKey("FreecraftCore.SpellEffectDataChunk<float>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.SpellEffectDataChunk<float>", "DmgMultiplier", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<float>("Effect1");

                            b1.Property<float>("Effect2");

                            b1.Property<float>("Effect3");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("DmgMultiplier")
                                .HasForeignKey("FreecraftCore.SpellEffectDataChunk<float>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.SpellTotemDataChunk<uint>", "TotemCategory", b1 =>
                        {
                            b1.Property<int>("SpellEntry<string>SpellId");

                            b1.Property<uint>("One");

                            b1.Property<uint>("Two");

                            b1.ToTable("Spell");

                            b1.HasOne("FreecraftCore.SpellEntry<string>")
                                .WithOne("TotemCategory")
                                .HasForeignKey("FreecraftCore.SpellTotemDataChunk<uint>", "SpellEntry<string>SpellId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("FreecraftCore.SpellRangeEntry<string>", b =>
                {
                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "Description1", b1 =>
                        {
                            b1.Property<uint>("SpellRangeEntry<string>SpellRangeId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("SpellRange");

                            b1.HasOne("FreecraftCore.SpellRangeEntry<string>")
                                .WithOne("Description1")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellRangeEntry<string>SpellRangeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("FreecraftCore.LocalizedStringDBC<string>", "Description2", b1 =>
                        {
                            b1.Property<uint>("SpellRangeEntry<string>SpellRangeId");

                            b1.Property<uint>("Flags");

                            b1.Property<string>("deDE");

                            b1.Property<string>("enCN");

                            b1.Property<string>("enTW");

                            b1.Property<string>("enUS");

                            b1.Property<string>("esES");

                            b1.Property<string>("esMX");

                            b1.Property<string>("frFR");

                            b1.Property<string>("itIT");

                            b1.Property<string>("koKR");

                            b1.Property<string>("ptPT");

                            b1.Property<string>("ruRU");

                            b1.ToTable("SpellRange");

                            b1.HasOne("FreecraftCore.SpellRangeEntry<string>")
                                .WithOne("Description2")
                                .HasForeignKey("FreecraftCore.LocalizedStringDBC<string>", "SpellRangeEntry<string>SpellRangeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
