using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FreecraftCore.DBC.Management.Migrations
{
    public partial class InitialSpellDBC : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Spell",
                columns: table => new
                {
                    SpellId = table.Column<uint>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Category = table.Column<uint>(nullable: false),
                    Dispel = table.Column<uint>(nullable: false),
                    Mechanic = table.Column<int>(nullable: false),
                    Attributes = table.Column<uint>(nullable: false),
                    AttributesEx = table.Column<uint>(nullable: false),
                    AttributesEx2 = table.Column<uint>(nullable: false),
                    AttributesEx3 = table.Column<uint>(nullable: false),
                    AttributesEx4 = table.Column<uint>(nullable: false),
                    AttributesEx5 = table.Column<uint>(nullable: false),
                    AttributesEx6 = table.Column<uint>(nullable: false),
                    AttributesEx7 = table.Column<uint>(nullable: false),
                    Stances = table.Column<ulong>(nullable: false),
                    StancesNot = table.Column<ulong>(nullable: false),
                    Targets = table.Column<uint>(nullable: false),
                    TargetCreatureType = table.Column<int>(nullable: false),
                    RequiresSpellFocus = table.Column<uint>(nullable: false),
                    FacingCasterFlags = table.Column<uint>(nullable: false),
                    CasterAuraState = table.Column<int>(nullable: false),
                    TargetAuraState = table.Column<int>(nullable: false),
                    CasterAuraStateNot = table.Column<int>(nullable: false),
                    TargetAuraStateNot = table.Column<int>(nullable: false),
                    CasterAuraSpell = table.Column<uint>(nullable: false),
                    TargetAuraSpell = table.Column<uint>(nullable: false),
                    ExcludeCasterAuraSpell = table.Column<uint>(nullable: false),
                    ExcludeTargetAuraSpell = table.Column<uint>(nullable: false),
                    CastingTimeIndex = table.Column<uint>(nullable: false),
                    RecoveryTime = table.Column<uint>(nullable: false),
                    CategoryRecoveryTime = table.Column<uint>(nullable: false),
                    InterruptFlags = table.Column<uint>(nullable: false),
                    AuraInterruptFlags = table.Column<uint>(nullable: false),
                    ChannelInterruptFlags = table.Column<uint>(nullable: false),
                    ProcFlags = table.Column<int>(nullable: false),
                    ProcChance = table.Column<uint>(nullable: false),
                    ProcCharges = table.Column<uint>(nullable: false),
                    MaxLevel = table.Column<uint>(nullable: false),
                    BaseLevel = table.Column<uint>(nullable: false),
                    SpellLevel = table.Column<uint>(nullable: false),
                    DurationIndex = table.Column<uint>(nullable: false),
                    PowerType = table.Column<uint>(nullable: false),
                    ManaCost = table.Column<uint>(nullable: false),
                    ManaCostPerlevel = table.Column<uint>(nullable: false),
                    ManaPerSecond = table.Column<uint>(nullable: false),
                    ManaPerSecondPerLevel = table.Column<uint>(nullable: false),
                    RangeIndex = table.Column<uint>(nullable: false),
                    Speed = table.Column<float>(nullable: false),
                    ModalNextSpell = table.Column<uint>(nullable: false),
                    StackAmount = table.Column<uint>(nullable: false),
                    ReagentsRequired_Totem_One = table.Column<uint>(nullable: false),
                    ReagentsRequired_Totem_Two = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentId_One = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Two = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Three = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Four = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Five = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Six = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Seven = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentId_Eight = table.Column<int>(nullable: false),
                    ReagentsRequired_ReagentCount_One = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Two = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Three = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Four = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Five = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Six = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Seven = table.Column<uint>(nullable: false),
                    ReagentsRequired_ReagentCount_Eight = table.Column<uint>(nullable: false),
                    EquippedItemClass = table.Column<int>(nullable: false),
                    EquippedItemSubClassMask = table.Column<int>(nullable: false),
                    EquippedItemInventoryTypeMask = table.Column<int>(nullable: false),
                    SpellEffectInformation_Effect_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_Effect_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_Effect_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectDieSides_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectDieSides_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectDieSides_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectRealPointsPerLevel_Effect1 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectRealPointsPerLevel_Effect2 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectRealPointsPerLevel_Effect3 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectBasePoints_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectBasePoints_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectBasePoints_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMechanic_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMechanic_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMechanic_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetA_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetA_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetA_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetB_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetB_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectImplicitTargetB_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectRadiusIndex_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectRadiusIndex_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectRadiusIndex_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectApplyAuraName_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectApplyAuraName_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectApplyAuraName_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectAmplitude_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectAmplitude_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectAmplitude_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectMultipleValue_Effect1 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectMultipleValue_Effect2 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectMultipleValue_Effect3 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectChainTarget_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectChainTarget_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectChainTarget_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectItemType_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectItemType_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectItemType_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectMiscValue_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMiscValue_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMiscValue_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMiscValueB_Effect1 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMiscValueB_Effect2 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectMiscValueB_Effect3 = table.Column<int>(nullable: false),
                    SpellEffectInformation_EffectTriggerSpell_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectTriggerSpell_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectTriggerSpell_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectPointsPerComboPoint_Effect1 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectPointsPerComboPoint_Effect2 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectPointsPerComboPoint_Effect3 = table.Column<float>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskA_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskA_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskA_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskB_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskB_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskB_Effect3 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskC_Effect1 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskC_Effect2 = table.Column<uint>(nullable: false),
                    SpellEffectInformation_EffectSpellClassMaskC_Effect3 = table.Column<uint>(nullable: false),
                    SpellVisual_One = table.Column<uint>(nullable: false),
                    SpellVisual_Two = table.Column<uint>(nullable: false),
                    SpellIconID = table.Column<uint>(nullable: false),
                    ActiveIconID = table.Column<uint>(nullable: false),
                    SpellPriority = table.Column<uint>(nullable: false),
                    ManaCostPercentage = table.Column<uint>(nullable: false),
                    StartRecoveryCategory = table.Column<uint>(nullable: false),
                    StartRecoveryTime = table.Column<uint>(nullable: false),
                    MaxTargetLevel = table.Column<uint>(nullable: false),
                    SpellFamilyName = table.Column<int>(nullable: false),
                    SpellFamilyFlags_One = table.Column<uint>(nullable: false),
                    SpellFamilyFlags_Two = table.Column<uint>(nullable: false),
                    SpellFamilyFlags_Three = table.Column<uint>(nullable: false),
                    MaxAffectedTargets = table.Column<uint>(nullable: false),
                    DmgClass = table.Column<int>(nullable: false),
                    PreventionType = table.Column<int>(nullable: false),
                    StanceBarOrder = table.Column<uint>(nullable: false),
                    DmgMultiplier_Effect1 = table.Column<float>(nullable: false),
                    DmgMultiplier_Effect2 = table.Column<float>(nullable: false),
                    DmgMultiplier_Effect3 = table.Column<float>(nullable: false),
                    MinFactionId = table.Column<uint>(nullable: false),
                    MinReputation = table.Column<uint>(nullable: false),
                    RequiredAuraVision = table.Column<uint>(nullable: false),
                    TotemCategory_One = table.Column<uint>(nullable: false),
                    TotemCategory_Two = table.Column<uint>(nullable: false),
                    AreaGroupId = table.Column<int>(nullable: false),
                    SchoolMask = table.Column<int>(nullable: false),
                    RuneCostID = table.Column<uint>(nullable: false),
                    SpellMissileID = table.Column<uint>(nullable: false),
                    PowerDisplayId = table.Column<uint>(nullable: false),
                    DamageCoeficient_Effect1 = table.Column<float>(nullable: false),
                    DamageCoeficient_Effect2 = table.Column<float>(nullable: false),
                    DamageCoeficient_Effect3 = table.Column<float>(nullable: false),
                    SpellDescriptionVariableID = table.Column<uint>(nullable: false),
                    SpellDifficultyId = table.Column<uint>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Spell", x => x.SpellId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Spell");
        }
    }
}
