namespace GladBot
{
	/// <summary>
	///
	/// </summary>
	public enum SpellSpecific
	{
		SPELL_SPECIFIC_NORMAL = 0,
		SPELL_SPECIFIC_SEAL = 1,
		SPELL_SPECIFIC_AURA = 3,
		SPELL_SPECIFIC_STING = 4,
		SPELL_SPECIFIC_CURSE = 5,
		SPELL_SPECIFIC_ASPECT = 6,
		SPELL_SPECIFIC_TRACKER = 7,
		SPELL_SPECIFIC_WARLOCK_ARMOR = 8,
		SPELL_SPECIFIC_MAGE_ARMOR = 9,
		SPELL_SPECIFIC_ELEMENTAL_SHIELD = 10,
		SPELL_SPECIFIC_MAGE_POLYMORPH = 11,
		SPELL_SPECIFIC_JUDGEMENT = 13,
		SPELL_SPECIFIC_WARLOCK_CORRUPTION = 17,
		SPELL_SPECIFIC_FOOD = 19,
		SPELL_SPECIFIC_DRINK = 20,
		SPELL_SPECIFIC_FOOD_AND_DRINK = 21,
		SPELL_SPECIFIC_PRESENCE = 22,
		SPELL_SPECIFIC_CHARM = 23,
		SPELL_SPECIFIC_SCROLL = 24,
		SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE = 25,
		SPELL_SPECIFIC_WARRIOR_ENRAGE = 26,
		SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT = 27,
		SPELL_SPECIFIC_HAND = 28,
		SPELL_SPECIFIC_PHASE = 29,
	};
}